apiVersion: v2
name: cert-manager
description: A Helm chart for cert-manager
type: application
version: 1.0.0
appVersion: "v1.14.4"
dependencies:
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
